#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef rti_me_cpp_hxx
#include "rti_me_cpp.hxx"
#endif
#include "wh_sm/wh_sm_history.h"
#include "rh_sm/rh_sm_history.h"

#include "Datatypes.h"
#include "DatatypesSupport.h"
#include "DatatypesPlugin.h"
#include "application_common.h"

class ProximityDataReaderListener : public DDSDataReaderListener
{

public:

    virtual void on_data_available(DDSDataReader *reader);
    virtual void on_requested_deadline_missed(
            DDSDataReader* reader,
            const DDS_RequestedDeadlineMissedStatus& status);
};

void ProximityDataReaderListener::on_data_available(DDSDataReader * reader) {

    DDS_ReturnCode_t retcode;

    ProximityDataDataReader *ProximityData_reader = NULL;
    ProximityData_reader = ProximityDataDataReader::narrow(reader);
    if (ProximityData_reader == NULL) {
        fprintf(stderr, "DataReader narrow error\n");
        return;
    }

    ProximityDataSeq data_seq;
    DDS_SampleInfoSeq info_seq;
    retcode = ProximityData_reader->take(
            data_seq,
            info_seq,
            DDS_LENGTH_UNLIMITED,
            DDS_ANY_SAMPLE_STATE,
            DDS_ANY_VIEW_STATE,
            DDS_ANY_INSTANCE_STATE);

    if (retcode == DDS_RETCODE_NO_DATA) {
        return;
    } else if (retcode != DDS_RETCODE_OK) {
        std::cerr << "take error " << retcode << std::endl;
        return;
    }

    for (int i = 0; i < data_seq.length(); ++i) {
        if (info_seq[i].valid_data) {
            printf("Received data\n");
            printf("Sensor ID = %s\n", data_seq[i].sensor_id);
            printf("Proximity (m) = %f\n\n", data_seq[i].proximity);
        }
    }

    retcode = ProximityData_reader->return_loan(data_seq, info_seq);
    if (retcode != DDS_RETCODE_OK) {
        std::cerr << "return loan error " << retcode << std::endl;
    }
}


void ProximityDataReaderListener::on_requested_deadline_missed(
            DDSDataReader* reader,
            const DDS_RequestedDeadlineMissedStatus& status) 
{
    std::cout << "We missed a deadline!!" << std::endl;
}

int subscriber_main_w_args(
        DDS_Long domain_id, 
        char *udp_intf, 
        char *peer,
        DDS_Long sleep_time, 
        DDS_Long count)
{
    ProximityDataReaderListener *listener  = new ProximityDataReaderListener();
    DDS_ReturnCode_t retcode;
    Application *application = NULL;

    try {

        application = new Application();
        if (application == NULL) {
            printf("failed Application new\n");
            throw "Application alloc";
        }

        retcode = application->initialize( 
                domain_id,
                udp_intf, 
                peer, 
                sleep_time, 
                count);
        if (retcode != DDS_RETCODE_OK) {
            throw "Application init";
        }

        DDSSubscriber *subscriber = NULL;
        subscriber = application->participant->create_subscriber(
            DDS_SUBSCRIBER_QOS_DEFAULT,NULL,
            DDS_STATUS_MASK_NONE);
        if (subscriber == NULL) {
            throw "subscriber";
        }

        // The *get_default_type_name() function is generated by rtiddsgen in 
        // the file DataTypesPlugin.cxx
        retcode = ProximityDataTypeSupport::register_type(
                    application->participant,
                    ProximityDataTypePlugin_get_default_type_name());
        if (retcode != DDS_RETCODE_OK) {
            throw "register ProximityData type";
        }

        DDSTopic *proximity_data_topic = NULL;
        proximity_data_topic = application->participant->create_topic(
                PROXIMITY_DATA_TOPIC_NAME, // this constant is defined in the IDL
                ProximityDataTypePlugin_get_default_type_name(),
                DDS_TOPIC_QOS_DEFAULT, 
                NULL,
                DDS_STATUS_MASK_NONE);
        if (proximity_data_topic == NULL) {
            throw "proximity_data_topic";
        } 

        DDS_DataReaderQos dr_qos;
        retcode = subscriber->get_default_datareader_qos(dr_qos);
        if (retcode != DDS_RETCODE_OK) {
            throw "dr_qos";
        }

        dr_qos.resource_limits.max_samples = 32;
        dr_qos.resource_limits.max_instances = 1;
        dr_qos.resource_limits.max_samples_per_instance = 32;
        dr_qos.reader_resource_limits.max_remote_writers = 10;
        dr_qos.reader_resource_limits.max_remote_writers_per_instance = 10;
        dr_qos.history.depth = 32;

        dr_qos.reliability.kind = DDS_BEST_EFFORT_RELIABILITY_QOS;
        dr_qos.deadline.period.sec = 0;
        dr_qos.deadline.period.nanosec = 500000000;

        DDSDataReader *datareader = NULL;
        datareader = subscriber->create_datareader(
            proximity_data_topic,
            dr_qos,
            listener,
            DDS_DATA_AVAILABLE_STATUS | DDS_REQUESTED_DEADLINE_MISSED_STATUS);

        if (datareader == NULL) {
            throw "datareader";
        }

        retcode = application->enable();
        if (retcode != DDS_RETCODE_OK) {
            throw "application enable";
        }

    } catch (const char *msg) {
        std::cerr << msg << std::endl;
        if (application != NULL) {
            delete application;
        }
        if (listener != NULL) {
            delete listener;
        }
        //DataReaderQos is automatically disposed by destructor

        return DDS_RETCODE_ERROR;
    }


    if (application->count != 0) {

        std::cout << "Running for " << application->count << 
                "seconds, press Ctrl-C to exit" << std::endl;
        OSAPI_Thread_sleep(application->count * 1000);

    } else {

        int sleep_loop_count =  (24 * 60 * 60) / 2000;
        int sleep_loop_left = (24 * 60 * 60) % 2000;

        std::cout << "Running for 24 hours, press Ctrl-C to exit" << std::endl;

        while (sleep_loop_count) {
            OSAPI_Thread_sleep(2000  * 1000); /* sleep is in ms */
            --sleep_loop_count;
        }

        OSAPI_Thread_sleep(sleep_loop_left * 1000);
    }

    if (application != NULL) {
        delete application;
    }

    if (listener != NULL) {
        delete listener;
    }

    //DataReaderQos is automatically disposed by destructor

    return DDS_RETCODE_OK;
}


int main(int argc, char **argv)
{
    DDS_Long i = 0;
    DDS_Long domain_id = 0;
    char *peer = NULL;
    char *udp_intf = NULL;
    DDS_Long sleep_time = 1000;
    DDS_Long count = 0;

    for (i = 1; i < argc; ++i)
    {
        if (!strcmp(argv[i], "-domain"))
        {
            ++i;
            if (i == argc)
            {
                printf("-domain <domain_id>\n");
                return -1;
            }
            domain_id = strtol(argv[i], NULL, 0);
        }
        else if (!strcmp(argv[i], "-udp_intf"))
        {
            ++i;
            if (i == argc)
            {
                printf("-udp_intf <interface>\n");
                return -1;
            }
            udp_intf = argv[i];
        }
        else if (!strcmp(argv[i], "-peer"))
        {
            ++i;
            if (i == argc)
            {
                printf("-peer <address>\n");
                return -1;
            }
            peer = argv[i];
        }
        else if (!strcmp(argv[i], "-sleep"))
        {
            ++i;
            if (i == argc)
            {
                printf("-sleep_time <sleep_time>\n");
                return -1;
            }
            sleep_time = strtol(argv[i], NULL, 0);
        }
        else if (!strcmp(argv[i], "-count"))
        {
            ++i;
            if (i == argc)
            {
                printf("-count <count>\n");
                return -1;
            }
            count = strtol(argv[i], NULL, 0);
        }
        else if (!strcmp(argv[i], "-h"))
        {
            Application::help(argv[0]);
            return 0;
        }
        else
        {
            printf("unknown option: %s\n", argv[i]);
            return -1;
        }
    }

    return subscriber_main_w_args(domain_id, udp_intf, peer, sleep_time, count);
}
